### ISSUE TITLE
Encoutered some problems 

### ISSUE THREAD

**Issue by zfn-zz** [niklasb/bspfuzz#3]
I am very interested in this fuzz, but I have encountered some problems when trying to use this fuzz.
1. You didn't mention the version of the dedicated server you used in the article. I tried to find some offsets based on some descriptions in the code to make bspfuzz work, but how do I determine if the offset I am looking for is correct?

2.I tried to test bspfuzz using AFL fuzz, but got some errors as shown.
<img width="1066" alt="afl_fork_server_error" src="https://user-images.githubusercontent.com/4680688/55312403-08264a00-5498-11e9-8fad-16730241ced8.png">
I have patched AFL fuzz with afl_patches.diff and the generated afl-fuzz works fine when using the -Q parameter to fuzz wget.Therefore, it looks like the error caused by bspfuzz, but the direct use of bspfuzz is  normal.
<img width="1014" alt="bspfuzz" src="https://user-images.githubusercontent.com/4680688/55313525-8e439000-549a-11e9-8c8f-7c62c1d28f02.png">

**Comment by niklasb** [comment]
Sorry, it was an older version and I couldn't upload the binaries due to licensing reasons... I guess at this point some manual effort would be required to dig up all the offsets.

**Comment by niklasb** [comment]
Actually, whatever. I added the files under https://github.com/niklasb/bspfuzz/tree/master/bin so you can correlate the patches I did

**Comment by zfn-zz** [comment]
These are very big help for me, thank you, I will try again later.

**Comment by zfn-zz** [comment]
I have fixed the wrong offset, but the problem is still not solved. I will debug the code later to try to solve the problem. If there is a new discovery, I will let u know.

**Comment by zfn-zz** [comment]
Finally I fixed this problem after reading the source code of AFL. This is the caused by AFL qemu mode.'CPU_TARGET=i386' should be setted before run the build_qemu_support.sh. If running code in x64 environment.
